apiVersion: v1
kind: Pod
metadata:
  name: myweb
  labels:
    environment: production
    app: nginx
spec:
  containers:
    - image: nginx:latest
      name: myweb
      ports:
        - containerPort: 80
          protocol: TCP
