apiVersion: apps/v1 
kind: Deployment 
metadata: 
  labels: 
    app: dp-web-apaches 
  name: dp-web-apaches 
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      app: dp-web-apaches 
  strategy: 
    type: RollingUpdate 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0 
  template: 
    metadata: 
      labels: 
        app: dp-web-apaches 
    spec: 
      containers: 
      - image: httpd:latest 
        name: httpd 
        ports: 
        - containerPort: 80 
        env:
        - name: ENV_KEYNAME_1
          valueFrom:
            configMapKeyRef:
              name: log-level-configmap
              key: LOG_LEVEL
        - name: ENV_KEYNAME_2
          valueFrom:
            configMapKeyRef:
              name: start-k8s
              key: k8s
