# 다음 조건에 맞는 Pod를 생성하세요 
# Pod name: myweb, image: nginx:1.14 
# CPU 200m, Memory 500Mi를 요구하고, CPU 1 Core, Memory 1Gi 제한 받는다. 
# Application 동작을 필요한 환경변수 DB=mydb를 포함한다. 
# namespace product에서 동작되어야 한다. 

apiVersion: v1
kind: Pod
metadata:
  name: myweb
  namespace: product
spec:
  containers:
  - name: myweb-nginx
    image: nginx:1.14
    env:
    - name: DB
      value: "mydb"
    resources:
      requests:
        cpu: 200m
        memory: 500Mi
      limits:
        cpu: 1
        memory: 1Gi
