apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webserver-1
  name: webserver-1
spec:
  containers:
  - image: nginx:1.14
    name: webserver-1
    ports:
    - containerPort: 80
      protocol: TCP
    - containerPort: 443
      protocol: TCP
  restartPolicy: Always
status: {}
