apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-2
spec:
  containers:
  - name: c1-nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: c2-ubuntu
    image: ubuntu:24.04
    command: ["/bin/bash"]
    args: ["-c", "while true; do echo 'Running'; sleep 10; done"]
#     image: nginx:1.14.4
      #    ports:
      #    - containerPort: 8080
