apiVersion: v1
kind: Pod
metadata:
  name: nginx-probe-httpget
spec:
  containers:
  - image: nginx:1.14
    name: nginx-probe-httpget
    livenessProbe:
      httpGet:
        path: /
        port: 80
