apiVersion: v1
kind: Service
metadata:
  name: ser-nginx
spec:
  type: LoadBalancer
  clusterIP: 10.99.0.1
  clusterIPs:
  - 10.99.0.1
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
