apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-1
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend-1
    matchExpressions:
      - key: version
        operator: In
        values: ["1.14","1.15"]
  template:
    metadata:
      labels:
        tier: frontend-1
        version: "1.14"
    spec:
      containers:
      - name: nginx
        image: nginx:1.14
