apiVersion: v1 
kind: Pod
metadata: 
  name: hostpath-types 
spec: 
  containers: 
  - name: container 
    image: busybox 
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"] 
    volumeMounts: 
    - name: dir-or-create 
      mountPath: /data/dir-or-create 
    - name: existing-dir 
      mountPath: /data/existing-dir 
    - name: file-or-create 
      mountPath: /data/file-or-create 
    - name: existing-file 
      mountPath: /data/existing-file 
  volumes: 
  - name: dir-or-create 
    hostPath: 
      path: /tmp/data/dir-or-create 
      type: DirectoryOrCreate 
  - name: existing-dir 
    hostPath: 
      path: /tmp/data/existing-dir 
      type: Directory 
  - name: file-or-create 
    hostPath: 
      path: /tmp/data/file-or-create 
      type: FileOrCreate 
  - name: existing-file 
    hostPath: 
      path: /tmp/data/existing-file 
      type: File 
