apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webserver-3
  name: webserver-3
spec:
  containers:
  - image: nginx:latest
    name: webserver-3
    ports:
    - containerPort: 80
      protocol: TCP
    - containerPort: 443
      protocol: TCP
  - image: centos:7
    name: centos7
    command:
    - sleep
    - "360000"
  - image: ubuntu:24.04
    name: ubuntu24
    command:
    - sleep
    - "360000"                                                           
  nodeName: node3.labs.local
  restartPolicy: Always
