apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
  namespace: wordpress
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: pv-mysql
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 10.10.8.3
    path: /data
