apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
spec:
  containers:
  - name: cpu-demo-ctr
    image: ubuntu:24.04 
    command:
    - sleep
    - "360000"
    resources:
      limits:
        cpu: "2"
      requests:
        cpu: "0.1"
