apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
spec:
  containers:
  - name: memory-demo-ctr
    image: ubuntu:24.04 
    command:
    - sleep
    - "360000"
    resources:
      limits:
        memory: "5Mi"
      requests:
        memory: "5Mi"
