apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-nginx
  labels:
    app: metallb
  namespace: metallb-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: metallb
  template:
    metadata:
      name: dep-nginx
      labels:
        app: metallb
    spec:
      containers:
      - name: nginx
        image: nginx:1.14
