apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nginx-canary-deployment 
spec: 
  replicas: 1  # Canary 버전의 파드 수 
  selector: 
    matchLabels: 
      app: nginx
      version: canary 
  template: 
    metadata: 
      labels: 
        app: nginx 
        version: canary 
    spec: 
      containers: 
      - name: nginx 
        image: nginx:1.15 
        ports: 
        - containerPort: 80 
