apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nginx-deployment 
spec: 
  replicas: 4 
  selector: 
    matchLabels: 
      app: nginx 
  template: 
    metadata: 
      labels: 
        app: nginx 
        version: "1.15" 
    spec: 
      containers: 
      - name: nginx 
        image: nginx:1.15 
        ports: 
        - containerPort: 80 
