apiVersion: v1
kind: Pod
metadata:
  name: nginx-probe-exec
spec:
  containers:
  - image: nginx:1.14
    name: nginx-probe-exec
    volumeMounts:
    - mountPath: /data
      name: directory
    - mountPath: /data/check.txt
      name: file
    livenessProbe:
      exec:
        command:
        - ls
        - /data/check.txt
  volumes:
  - name: directory 
    hostPath:
      path: /data
      type: DirectoryOrCreate
  - name: file
    hostPath:
      path: /data/check.txt
      type: FileOrCreate
