apiVersion: apps/v1 
kind: Deployment 
metadata: 
  labels: 
    app: dp-web-apaches 
  name: dp-web-apaches 
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      app: dp-web-apaches 
  strategy: 
    type: RollingUpdate 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0 
  template: 
    metadata: 
      labels: 
        app: dp-web-apaches 
    spec: 
      containers: 
      - image: httpd:latest 
        name: httpd 
        ports: 
        - containerPort: 80 
        volumeMounts:
        - name: configmap-volume
          mountPath: /etc/config
      volumes:
      - name: configmap-volume
        configMap:
          name: start-k8s
          items:
          - key: k8s
            path: k8s_fullname
