apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webserver-2
  name: webserver-2
spec:
  containers:
  - image: nginx:1.14
    name: webserver-2
    ports:
    - containerPort: 80
      protocol: TCP
    - containerPort: 443
      protocol: TCP
  nodeName: node3.labs.local
  restartPolicy: Always
status: {}
